import React from 'react'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'

import Providers from '@/redux/provider'
import AuthProvider from '@/auth/AuthProvider'

import type { Metadata } from 'next'

import './globals.css'

export const revalidate: number = 0

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'React-next admin panel',
  description: 'Generated by create next app'
}

export default async function RootLayout ({ children }: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { session }
  } = await supabase.auth.getSession()

  const accessToken: string | null = session?.access_token ?? null

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthProvider accessToken={accessToken}>
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  )
}
